### ISSUE TITLE
解压密码已经被破解了

### ISSUE THREAD

**Issue by XCRail** [XCRailway/XCRailMinecraftBatchhAder#1]
密码：plotworldxcrail6025852004danticrack510

请修复。

**Comment by brainbush** [comment]
https://github.com/XCRailway/XCRailMinecraftBatchhAder/blob/master/index.bat#L57

**Comment by brainbush** [comment]
[这里](https://github.com/XCRailway/XCRailMinecraftBatchhAder/blob/master/index.bat#L57)
`if %%pass%%==jb51 goto ok`


[还有这里](https://github.com/XCRailway/XCRailMinecraftBatchhAder/blob/master/assents/mccore/xcrail.bat#L8)
`unrar.exe x clientarc20160701.xcdata -pplotworldxcrail6025852004danticrack510 -r -y`

话说这样明文写密码真的没问题？

> 温馨提示：现在为了防止熊孩子破解客户端核心，本人对客户端核心文件做了加密压缩处理，密码长达30多位且没人知道，只有天知地知小曹知。由于每次启动客户端都会解压客户端，每次退出时都会删除客户端。所以客户端启动会慢很多，如果你修改了MC里的设置，下次启动会自动还原。敬请谅解。

**Comment by XCRailway** [comment]
。。。 没事 破解了也没事 这东西是给小学生用的 即使我不明文，大神也能破解
